# Generated by Django 2.1.7 on 2021-08-10 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210810_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 10, 18, 15, 29, 227477)),
        ),
    ]
